###
GET http://127.0.0.1:8080/all

###
GET http://127.0.0.1:8080/1
###
GET http://127.0.0.1:8080/2

###
POST http://127.0.0.1:8080
Content-Type: application/x-www-form-urlencoded

title=assa&body=ASSA
###
POST http://127.0.0.1:8080/2/upd
Content-Type: application/x-www-form-urlencoded

title=assa-2&body=ASSA-2
###
POST http://127.0.0.1:8080/5/del
